Repository RobbieTheWagner/ember-shepherd, pull requests merged in 2018-09, with the labels that each got.

#237 remove required buttons options
  addon/services/tour.js
Labels: enhancement

#245 Stop disabling target element pointer events
  README.md
  addon/services/tour.js
  tests/acceptance/ember-shepherd-test.js
  tests/dummy/app/styles/app.scss
  tests/dummy/app/templates/application.hbs
Labels: breaking

#243 Rename `defaults` to `defaultStepOptions`.
  README.md
  addon/services/tour.js
  package.json
  tests/acceptance/ember-shepherd-test.js
  tests/dummy/app/routes/application.js
  tests/dummy/app/templates/application.hbs
  yarn.lock
Labels: 4.0, breaking

#241 Change builtInButtons to buttons
  README.md
  addon/services/tour.js
  package.json
  tests/acceptance/buttons-test.js
  tests/acceptance/ember-shepherd-test.js
  tests/data.js
  tests/dummy/app/data.js
  tests/unit/services/tour-test.js
  yarn.lock
Labels: 4.0, breaking

#247 Remove cleanupShepherdElements
  addon/services/tour.js
  addon/utils.js
  tests/acceptance/ember-shepherd-test.js
Labels: 4.0, bug

#248 Implement SVG-based modal mode
  README.md
  addon/services/tour.js
  addon/styles/addon.css
  addon/utils/dom.js
  addon/utils/modal.js
  tests/acceptance/ember-shepherd-test.js
  tests/data.js
  tests/dummy/app/data.js
  tests/dummy/app/templates/application.hbs
  tests/unit/services/tour-test.js
Labels: 4.0, breaking

#251 Use Ember.set to set `this.tourObject`
  addon/services/tour.js
Labels: bug

#250 Hide modal when hiding the current step
  README.md
  addon/services/tour.js
Labels: enhancement
